name: AWMKit

options:
  bundleIdPrefix: com.awmkit
  xcodeVersion: "26.0"
  deploymentTarget:
    macOS: "26.0"
  developmentLanguage: zh-Hans
  createIntermediateGroups: true
  usesTabs: false
  indentWidth: 4
  tabWidth: 4

settings:
  base:
    MARKETING_VERSION: 0.1.3
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: 5.9
    MACOSX_DEPLOYMENT_TARGET: 26.0
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    ENABLE_HARDENED_RUNTIME: YES
    ENABLE_APP_SANDBOX: NO

packages:
  AWMKit:
    url: https://github.com/aspect-ratio/awmkit
    # 使用本地路径开发
    path: ../bindings/swift

targets:
  AWMKitApp:
    type: application
    platform: macOS
    deploymentTarget: "26.0"

    sources:
      - path: AWMKit/Sources
        name: Sources
        type: group
        createIntermediateGroups: true
      - path: AWMKit/Resources
        name: Resources
        type: group
        buildPhase: resources

    dependencies:
      - package: AWMKit
        product: AWMKit

    settings:
      base:
        PRODUCT_NAME: AWMKit
        PRODUCT_MODULE_NAME: AWMKitApp
        PRODUCT_BUNDLE_IDENTIFIER: com.awmkit.app
        INFOPLIST_FILE: AWMKit/Info.plist
        CODE_SIGN_ENTITLEMENTS: AWMKit/AWMKit.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_OBJC_BRIDGING_HEADER: ""

        # 运行时搜索路径
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
          - "@loader_path/../Frameworks"

        # 框架链接（Rust 库通过 Swift Package 链接）
        OTHER_LDFLAGS:
          - $(inherited)
          - -framework Security
          - -framework Foundation
          - -framework UniformTypeIdentifiers

        # Swift 编译器设置
        SWIFT_OPTIMIZATION_LEVEL: -Onone
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG

      Debug:
        SWIFT_OPTIMIZATION_LEVEL: -Onone

      Release:
        SWIFT_OPTIMIZATION_LEVEL: -O
        SWIFT_COMPILATION_MODE: wholemodule

schemes:
  AWMKit:
    build:
      targets:
        AWMKitApp: all
    run:
      config: Debug
      commandLineArguments:
        "": true
      environmentVariables:
        - variable: RUST_BACKTRACE
          value: "1"
          isEnabled: true
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

# 聚合目标（可选）- 用于文档生成等
aggregateTargets: {}
