name: AWMKit

options:
  bundleIdPrefix: com.awmkit
  xcodeVersion: "26.0"
  deploymentTarget:
    macOS: "26.0"
  developmentLanguage: zh-Hans
  createIntermediateGroups: true
  usesTabs: false
  indentWidth: 4
  tabWidth: 4

settings:
  base:
    MARKETING_VERSION: 0.1.3
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: 5.9
    MACOSX_DEPLOYMENT_TARGET: 26.0
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    ENABLE_HARDENED_RUNTIME: YES
    ENABLE_APP_SANDBOX: NO

packages:
  AWMKit:
    url: https://github.com/aspect-ratio/awmkit
    # 使用本地路径开发
    path: ../bindings/swift

targets:
  AWMKitApp:
    type: application
    platform: macOS
    deploymentTarget: "26.0"

    sources:
      - path: AWMKit/Sources
        name: Sources
        type: group
        createIntermediateGroups: true
      - path: AWMKit/Resources
        name: Resources
        type: group
        buildPhase: resources

    dependencies:
      - package: AWMKit
        product: AWMKit

    preBuildScripts:
      - name: Build Rust Core (ffi,bundled,app)
        basedOnDependencyAnalysis: false
        script: |
          set -eu
          if [ -x /opt/homebrew/bin/brew ]; then
            eval "$(/opt/homebrew/bin/brew shellenv)"
          elif [ -x /usr/local/bin/brew ]; then
            eval "$(/usr/local/bin/brew shellenv)"
          fi
          if ! command -v cargo >/dev/null 2>&1; then
            if [ -f "$HOME/.cargo/env" ]; then
              . "$HOME/.cargo/env"
            fi
          fi
          if ! command -v cargo >/dev/null 2>&1; then
            echo "error: cargo not found. Install Rust toolchain first."
            exit 1
          fi
          if command -v brew >/dev/null 2>&1; then
            FF_PREFIX="$(brew --prefix ffmpeg 2>/dev/null || true)"
            if [ -n "${FF_PREFIX}" ] && [ -d "${FF_PREFIX}/lib/pkgconfig" ]; then
              export PKG_CONFIG_PATH="${FF_PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH:-}"
              export LIBRARY_PATH="${FF_PREFIX}/lib:${LIBRARY_PATH:-}"
              export CPATH="${FF_PREFIX}/include:${CPATH:-}"
            fi
          fi
          if ! command -v pkg-config >/dev/null 2>&1 || ! pkg-config --exists libavutil libavformat libavcodec libavfilter libswresample; then
            echo "error: FFmpeg dev packages not found for ffmpeg-sys-next."
            echo "hint: brew install pkgconf ffmpeg"
            echo "hint: ensure pkg-config can resolve libav*.pc under \$(brew --prefix ffmpeg)/lib/pkgconfig"
            exit 1
          fi
          cd "$SRCROOT/.."
          echo "[awmkit] cargo build --release --features ffi,bundled,app"
          cargo build --release --features ffi,bundled,app

    settings:
      base:
        PRODUCT_NAME: AWMKit
        PRODUCT_MODULE_NAME: AWMKitApp
        PRODUCT_BUNDLE_IDENTIFIER: com.awmkit.app
        INFOPLIST_FILE: AWMKit/Info.plist
        CODE_SIGN_ENTITLEMENTS: AWMKit/AWMKit.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_OBJC_BRIDGING_HEADER: ""

        # 运行时搜索路径
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
          - "@loader_path/../Frameworks"

        # 框架链接（Rust 库通过 Swift Package 链接）
        OTHER_LDFLAGS:
          - $(inherited)
          - -framework Security
          - -framework Foundation
          - -framework UniformTypeIdentifiers

        # Swift 编译器设置
        SWIFT_OPTIMIZATION_LEVEL: -Onone
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG

      Debug:
        SWIFT_OPTIMIZATION_LEVEL: -Onone

      Release:
        SWIFT_OPTIMIZATION_LEVEL: -O
        SWIFT_COMPILATION_MODE: wholemodule

schemes:
  AWMKit:
    build:
      targets:
        AWMKitApp: all
    run:
      config: Debug
      commandLineArguments:
        "": true
      environmentVariables:
        - variable: RUST_BACKTRACE
          value: "1"
          isEnabled: true
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

# 聚合目标（可选）- 用于文档生成等
aggregateTargets: {}
